---
language: ruby
rvm:
  - 1.9.3

services: mysql
cache: bundler
before_script: "./bin/ci/before_script"

branches:
  only:
    - master

notifications:
  recipients:
    - sipple@trustarts.org
    - ferguson@trustarts.org
  irc: "irc.freenode.org#pghtrustarts"