---
language: ruby
rvm:
  - 1.9.3

services: mysql

before_script:
  - cp spec/ci/database.mysql.yml config/database.yml;
  - mysql -e 'create database radiant_test;'
  - rake db:migrate
  - rake db:migrate:extensions


branches:
  only:
    - master

notifications:
  recipients:
    - sipple@trustarts.org
    - ferguson@trustarts.org
  irc: "irc.freenode.org#pghtrustarts"