---
language: ruby
rvm:
  - 1.9.3
  - 2.1.5

services: mysql

before_script:
  - cp spec/ci/database.mysql.yml config/database.yml;
  - mysql -e 'create database radiant_test;'
  - bundle exec rake db:migrate
  - bundle exec rake db:migrate:extensions


script:
  - bundle exec rake spec

branches:
  only:
    - master

notifications:
  recipients:
    - sipple@trustarts.org
    - ferguson@trustarts.org
  irc: "irc.freenode.org#pghtrustarts"
